# services:
  # load-balance:
  #   image: nginx:latest
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.3"
  #         memory: "40MB"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     # - ./tmp:/var/run/sockets
  #   networks:
  #     - backend
  #   ports:
  #     - 9999:9999
    # depends_on:
    #   - api1
    #   - api2

  # load-balance:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - MAX_CONNECTIONS=10
  #   networks:
  #     # - backend
  #     - payment-processor
  #   ports:
  #     - 9999:9999
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "32"
  #         memory: "150MB"

  # api1: &api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   hostname: api1
  #   environment:
  #     - UNIX_SOCKET_PATH=/var/run/sockets/api1.sock
  #   volumes:
  #     - ./tmp:/var/run/sockets
  #   networks:
  #     - backend
  #     - payment-processor
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.40"
  #         memory: "150MB"
  # api2:
  #   <<: *api
  #   hostname: api2
  #   environment:
  #     - UNIX_SOCKET_PATH=/var/run/sockets/api2.sock

services:
  load-balance:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
      - payment-processor
    ports:
      - 9999:9999
    volumes:
    - ./dev/shm:/var/run/sockets
    environment:
      - SOCKET_DIR=/var/run/sockets
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "20MB"

  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    environment:
      - SOCKET_DIR=/var/run/sockets
      - MODE=worker
    volumes:
      - ./dev/shm:/var/run/sockets
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "150MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - MODE=worker
      - SOCKET_DIR=/var/run/sockets
      - HOST=api2
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

# services:
#   load-balance:
#     image: lpj145/rinha-lb:1.03
#     networks:
#       - backend
#       - payment-processor
#     ports:
#       - 9999:9999
#     deploy:
#       resources:
#         limits:
#           cpus: "0.2"
#           memory: "20MB"
# networks:
#   backend:
#     driver: bridge
#   payment-processor:
#     external: true